# Generated by tools/generate_agent.py; edit the generator.
execute unless dimension minecraft:overworld run return 0
execute unless function npcraft:action/bounds run return 0
$execute unless loaded $(x) $(y) $(z) run return 0
$execute unless block $(x) $(y) $(z) $(kind) run return 0
# Never harvest the support underneath any NPC body or player.
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~1 ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return 0
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~1 ~0.5 if entity @a[distance=..0.9] run return 0
function npcraft:work/sight with entity @s data.agent.target
execute unless score #visible np.tmp matches 1 run return 0
return 1
