# Generated by tools/generate_agent.py; edit the generator.
# Staged inventory is unpublished until removal succeeds; repeat all geometric checks.
execute unless score #iv_ok np.tmp matches 1 run return 0
execute unless function npcraft:action/valid run return run function npcraft:agent/failed
$execute store success score #removed np.tmp run setblock $(x) $(y) $(z) minecraft:air
execute unless score #removed np.tmp matches 1 run return 0
function npcraft:inventory/commit
execute if score #tool_slot np.tmp matches 0..35 store result storage npcraft:inventory tool.i int 1 run scoreboard players get #tool_slot np.tmp
execute if score #tool_slot np.tmp matches 0..35 run function npcraft:inventory/wear with storage npcraft:inventory tool
execute store result score #mined np.tmp run data get entity @s data.agent.mined
scoreboard players add #mined np.tmp 1
execute store result entity @s data.agent.mined int 1 run scoreboard players get #mined np.tmp
function npcraft:agent/invalidate
