# Generated by tools/generate_agent.py; edit the generator.
scoreboard players set @s np.status 3
function npcraft:work/swing with entity @s data
execute unless score @s np.dig matches 1.. run function npcraft:action/start
execute if score #now np.sys < @s np.dig run return 0
function npcraft:inventory/begin
function npcraft:inventory/add_staged with entity @s data.agent.request
execute unless score #iv_ok np.tmp matches 1 run return run function npcraft:agent/full
function npcraft:action/commit with entity @s data.agent.target
