# Generated by tools/generate_agent.py; edit the generator.
data remove entity @s data.agent.hand
scoreboard players set #tool_slot np.tmp -1
data modify entity @s data.agent.request set value {stack:{id:"minecraft:oak_log",count:1},max:64}
data modify entity @s data.agent.duration set value 60
function npcraft:action/cut
