# Generated by tools/generate_agent.py; edit the generator.
execute unless function npcraft:action/valid run return run function npcraft:agent/failed
# Whitelist dispatch validates drop/tool rules instead of trusting a supplied drop ID.
execute if data entity @s data.agent.target{kind:"minecraft:oak_log"} run return run function npcraft:action/log
execute if data entity @s data.agent.target{kind:"minecraft:stone"} run return run function npcraft:action/stone
execute if data entity @s data.agent.target{kind:"minecraft:cobblestone"} run return run function npcraft:action/stone
return 0
