# Generated by tools/generate_agent.py; edit the generator.
execute unless score #iv_ok np.tmp matches 1 run return 0
execute unless function npcraft:action/bounds run return 0
$execute unless block $(x) $(y) $(z) minecraft:air run return 0
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless entity @s[distance=0.9..2] run return 0
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @a[distance=..0.9] run return 0
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return 0
$execute store success score #placed np.tmp run setblock $(x) $(y) $(z) minecraft:crafting_table keep
execute unless score #placed np.tmp matches 1 run return 0
function npcraft:inventory/commit
data modify entity @s data.agent.station set from entity @s data.agent.target
function npcraft:agent/invalidate
