# Generated by tools/generate_agent.py; edit the generator.
scoreboard players operation @s np.dig = #now np.sys
execute store result score #duration np.tmp run data get entity @s data.agent.duration
scoreboard players operation @s np.dig += #duration np.tmp
