# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/select_pick
execute unless score #tool_slot np.tmp matches 0..35 run return run function npcraft:agent/invalidate
data modify entity @s data.agent.request set value {stack:{id:"minecraft:cobblestone",count:1},max:64}
data modify entity @s data.agent.duration set value 30
function npcraft:action/cut
