# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"cobblestone"}
execute if score #iv_have np.tmp matches 2.. run return 1
function npcraft:inventory/select_pick
execute unless score #tool_slot np.tmp matches 0..35 run return run function npcraft:planner/need/wooden_pickaxe_1
execute unless data entity @s data.agent{resource:"cobblestone"} run function npcraft:agent/invalidate
data modify entity @s data.agent.resource set value "cobblestone"
data modify entity @s data.agent.task set value "gather_cobblestone"
function npcraft:agent/gather
return 0
