# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"crafting_table"}
execute if score #iv_have np.tmp matches 1.. run return 1
function npcraft:inventory/count {kind:"oak_planks"}
execute unless score #iv_have np.tmp matches 4.. run return run function npcraft:planner/need/oak_planks_4
function npcraft:craft/recipes/crafting_table
return 0
