# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"furnace"}
execute if score #iv_have np.tmp matches 1.. run return 1
execute unless function npcraft:craft/station_valid run return run function npcraft:planner/station
function npcraft:inventory/count {kind:"cobblestone"}
execute unless score #iv_have np.tmp matches 8.. run return run function npcraft:planner/need/cobblestone_8
data modify entity @s data.dest set from entity @s data.agent.station
data modify entity @s data.dest.range set value 1
function npcraft:nav/plan
execute unless score #arrived np.tmp matches 1 run return 0
function npcraft:craft/recipes/furnace
return 0
