# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"oak_log"}
execute if score #iv_have np.tmp matches 1.. run return 1
execute unless data entity @s data.agent{resource:"oak_log"} run function npcraft:agent/invalidate
data modify entity @s data.agent.resource set value "oak_log"
data modify entity @s data.agent.task set value "gather_oak_log"
function npcraft:agent/gather
return 0
