# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"oak_planks"}
execute if score #iv_have np.tmp matches 4.. run return 1
function npcraft:inventory/count {kind:"oak_log"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/oak_log_1
function npcraft:craft/recipes/oak_planks
return 0
