# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"stone_sword"}
execute if score #iv_have np.tmp matches 1.. run return 1
execute unless function npcraft:craft/station_valid run return run function npcraft:planner/station
function npcraft:inventory/count {kind:"cobblestone"}
execute unless score #iv_have np.tmp matches 2.. run return run function npcraft:planner/need/cobblestone_2
function npcraft:inventory/count {kind:"stick"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stick_1
data modify entity @s data.dest set from entity @s data.agent.station
data modify entity @s data.dest.range set value 1
function npcraft:nav/plan
execute unless score #arrived np.tmp matches 1 run return 0
function npcraft:craft/recipes/stone_sword
return 0
