# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"wooden_pickaxe"}
execute if score #iv_have np.tmp matches 1.. run return 1
execute unless function npcraft:craft/station_valid run return run function npcraft:planner/station
function npcraft:inventory/count {kind:"oak_planks"}
execute unless score #iv_have np.tmp matches 3.. run return run function npcraft:planner/need/oak_planks_3
function npcraft:inventory/count {kind:"stick"}
execute unless score #iv_have np.tmp matches 2.. run return run function npcraft:planner/need/stick_2
data modify entity @s data.dest set from entity @s data.agent.station
data modify entity @s data.dest.range set value 1
function npcraft:nav/plan
execute unless score #arrived np.tmp matches 1 run return 0
function npcraft:craft/recipes/wooden_pickaxe
return 0
