# Generated by tools/generate_agent.py; edit the generator.
execute unless function npcraft:craft/near_station run return 0
function npcraft:inventory/begin
function npcraft:inventory/take_staged {kind:"cobblestone",count:8}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:inventory/add_staged {stack:{id:"minecraft:furnace",count:1},max:64}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:inventory/commit
execute store result score #crafted np.tmp run data get entity @s data.agent.crafted
scoreboard players add #crafted np.tmp 1
execute store result entity @s data.agent.crafted int 1 run scoreboard players get #crafted np.tmp
data modify entity @s data.agent.task set value "crafted_furnace"
return 1
