# Generated by tools/generate_agent.py; edit the generator.
execute unless function npcraft:craft/near_station run return 0
function npcraft:inventory/begin
function npcraft:inventory/take_staged {kind:"cobblestone",count:3}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:inventory/take_staged {kind:"stick",count:2}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:inventory/add_staged {stack:{id:"minecraft:stone_pickaxe",count:1},max:1}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:inventory/commit
execute store result score #crafted np.tmp run data get entity @s data.agent.crafted
scoreboard players add #crafted np.tmp 1
execute store result entity @s data.agent.crafted int 1 run scoreboard players get #crafted np.tmp
data modify entity @s data.agent.task set value "crafted_stone_pickaxe"
return 1
