# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/begin
function npcraft:inventory/add_staged with entity @s data.agent.request
execute if score #iv_ok np.tmp matches 1 run function npcraft:inventory/commit
