# Generated by tools/generate_agent.py; edit the generator.
execute if score #iv_remaining np.tmp matches 0 run return 0
execute if score #iv_i np.tmp matches 36.. run return 0
execute store result storage npcraft:inventory cursor.i int 1 run scoreboard players get #iv_i np.tmp
function npcraft:inventory/add_slot with storage npcraft:inventory cursor
scoreboard players add #iv_i np.tmp 1
function npcraft:inventory/add_loop
