# Generated by tools/generate_agent.py; edit the generator.
$execute unless data storage npcraft:inventory bag[$(i)].item run return 0
$execute store result score #iv_limit np.tmp run data get storage npcraft:inventory bag[$(i)].max
execute unless score #iv_limit np.tmp = #iv_max np.tmp run return 0
$data modify storage npcraft:inventory probe set from storage npcraft:inventory bag[$(i)].item
data remove storage npcraft:inventory probe.count
execute store success score #iv_different np.tmp run data modify storage npcraft:inventory probe set from storage npcraft:inventory key
execute if score #iv_different np.tmp matches 1 run return 0
$execute store result score #iv_count np.tmp run data get storage npcraft:inventory bag[$(i)].item.count
scoreboard players operation #iv_room np.tmp = #iv_max np.tmp
scoreboard players operation #iv_room np.tmp -= #iv_count np.tmp
execute unless score #iv_room np.tmp matches 1.. run return 0
scoreboard players operation #iv_room np.tmp < #iv_remaining np.tmp
scoreboard players operation #iv_count np.tmp += #iv_room np.tmp
scoreboard players operation #iv_remaining np.tmp -= #iv_room np.tmp
$execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
