# Generated by tools/generate_agent.py; edit the generator.
scoreboard players set #iv_ok np.tmp 0
execute unless score #iv_ready np.tmp matches 1 run return 0
$data modify storage npcraft:inventory incoming set value $(stack)
$scoreboard players set #iv_max np.tmp $(max)
execute unless score #iv_max np.tmp matches 1..99 run return 0
execute unless data storage npcraft:inventory incoming.id run return 0
scoreboard players set #iv_remaining np.tmp 0
execute store result score #iv_remaining np.tmp run data get storage npcraft:inventory incoming.count
execute unless score #iv_remaining np.tmp matches 1..3564 run return 0
data modify storage npcraft:inventory key set from storage npcraft:inventory incoming
data remove storage npcraft:inventory key.count
scoreboard players set #iv_i np.tmp 0
function npcraft:inventory/add_loop
scoreboard players set #iv_i np.tmp 0
function npcraft:inventory/empty_loop
execute if score #iv_remaining np.tmp matches 0 run scoreboard players set #iv_ok np.tmp 1
