# Generated by tools/generate_agent.py; edit the generator.
scoreboard players set #iv_ok np.tmp 0
scoreboard players set #iv_ready np.tmp 0
function npcraft:agent/init
execute unless data entity @s data.agent{schema:1} run return 0
execute store result score #iv_length np.tmp run data get entity @s data.agent.bag
execute unless score #iv_length np.tmp matches 36 run return 0
scoreboard players set #iv_ready np.tmp 1
data modify storage npcraft:inventory bag set from entity @s data.agent.bag
scoreboard players set #iv_ok np.tmp 0
