# Generated by tools/generate_agent.py; edit the generator.
function npcraft:agent/init
data modify storage npcraft:inventory bag set from entity @s data.agent.bag
scoreboard players set #iv_ok np.tmp 0
