# Generated by tools/generate_agent.py; edit the generator.
execute unless score #iv_ok np.tmp matches 1 run return 0
data modify entity @s data.agent.bag set from storage npcraft:inventory bag
return 1
