# Generated by tools/generate_agent.py; edit the generator.
$execute if data entity @s data.agent.bag[0].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[0].item.count
$execute if data entity @s data.agent.bag[0].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[1].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[1].item.count
$execute if data entity @s data.agent.bag[1].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[2].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[2].item.count
$execute if data entity @s data.agent.bag[2].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[3].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[3].item.count
$execute if data entity @s data.agent.bag[3].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[4].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[4].item.count
$execute if data entity @s data.agent.bag[4].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[5].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[5].item.count
$execute if data entity @s data.agent.bag[5].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[6].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[6].item.count
$execute if data entity @s data.agent.bag[6].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[7].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[7].item.count
$execute if data entity @s data.agent.bag[7].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[8].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[8].item.count
$execute if data entity @s data.agent.bag[8].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[9].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[9].item.count
$execute if data entity @s data.agent.bag[9].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[10].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[10].item.count
$execute if data entity @s data.agent.bag[10].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[11].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[11].item.count
$execute if data entity @s data.agent.bag[11].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[12].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[12].item.count
$execute if data entity @s data.agent.bag[12].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[13].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[13].item.count
$execute if data entity @s data.agent.bag[13].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[14].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[14].item.count
$execute if data entity @s data.agent.bag[14].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[15].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[15].item.count
$execute if data entity @s data.agent.bag[15].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[16].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[16].item.count
$execute if data entity @s data.agent.bag[16].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[17].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[17].item.count
$execute if data entity @s data.agent.bag[17].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[18].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[18].item.count
$execute if data entity @s data.agent.bag[18].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[19].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[19].item.count
$execute if data entity @s data.agent.bag[19].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[20].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[20].item.count
$execute if data entity @s data.agent.bag[20].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[21].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[21].item.count
$execute if data entity @s data.agent.bag[21].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[22].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[22].item.count
$execute if data entity @s data.agent.bag[22].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[23].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[23].item.count
$execute if data entity @s data.agent.bag[23].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[24].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[24].item.count
$execute if data entity @s data.agent.bag[24].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[25].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[25].item.count
$execute if data entity @s data.agent.bag[25].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[26].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[26].item.count
$execute if data entity @s data.agent.bag[26].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[27].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[27].item.count
$execute if data entity @s data.agent.bag[27].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[28].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[28].item.count
$execute if data entity @s data.agent.bag[28].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[29].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[29].item.count
$execute if data entity @s data.agent.bag[29].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[30].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[30].item.count
$execute if data entity @s data.agent.bag[30].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[31].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[31].item.count
$execute if data entity @s data.agent.bag[31].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[32].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[32].item.count
$execute if data entity @s data.agent.bag[32].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[33].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[33].item.count
$execute if data entity @s data.agent.bag[33].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[34].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[34].item.count
$execute if data entity @s data.agent.bag[34].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
$execute if data entity @s data.agent.bag[35].item{id:"minecraft:$(kind)"} store result score #iv_one np.tmp run data get entity @s data.agent.bag[35].item.count
$execute if data entity @s data.agent.bag[35].item{id:"minecraft:$(kind)"} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp
