# Generated by tools/generate_agent.py; edit the generator.
$execute store success score #iv_dropped np.tmp run summon minecraft:item ~ ~0.5 ~ {Item:$(item),PickupDelay:0s}
$execute if score #iv_dropped np.tmp matches 1 run data modify entity @s data.agent.bag[$(i)] set value {}
