# Generated by tools/generate_agent.py; edit the generator.
execute unless data entity @s data.agent run return 0
scoreboard players set #iv_i np.tmp 0
function npcraft:inventory/drop_loop
data remove entity @s data.agent.hand
