# Generated by tools/generate_agent.py; edit the generator.
execute if score #iv_i np.tmp matches 36.. run return 0
execute store result storage npcraft:inventory drop.i int 1 run scoreboard players get #iv_i np.tmp
function npcraft:inventory/drop_slot with storage npcraft:inventory drop
scoreboard players add #iv_i np.tmp 1
function npcraft:inventory/drop_loop
