# Generated by tools/generate_agent.py; edit the generator.
$execute unless data entity @s data.agent.bag[$(i)].item run return 0
$data modify storage npcraft:inventory drop.item set from entity @s data.agent.bag[$(i)].item
function npcraft:inventory/drop_item with storage npcraft:inventory drop
