# Generated by tools/generate_agent.py; edit the generator.
$execute if data storage npcraft:inventory bag[$(i)].item run return 0
scoreboard players operation #iv_count np.tmp = #iv_remaining np.tmp
scoreboard players operation #iv_count np.tmp < #iv_max np.tmp
$data modify storage npcraft:inventory bag[$(i)] set value {}
$data modify storage npcraft:inventory bag[$(i)].item set from storage npcraft:inventory incoming
$execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
$execute store result storage npcraft:inventory bag[$(i)].max int 1 run scoreboard players get #iv_max np.tmp
scoreboard players operation #iv_remaining np.tmp -= #iv_count np.tmp
