# Generated by tools/generate_agent.py; edit the generator.
execute unless items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand * run return 0
        function npcraft:inventory/begin
        data modify entity @s data.agent.request set value {max:0}
        data modify entity @s data.agent.request.stack set from entity @a[tag=npcraft.actor,limit=1] SelectedItem
    execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=1] run data modify entity @s data.agent.request.max set value 1
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=2] run data modify entity @s data.agent.request.max set value 2
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=3] run data modify entity @s data.agent.request.max set value 3
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=4] run data modify entity @s data.agent.request.max set value 4
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=5] run data modify entity @s data.agent.request.max set value 5
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=6] run data modify entity @s data.agent.request.max set value 6
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=7] run data modify entity @s data.agent.request.max set value 7
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=8] run data modify entity @s data.agent.request.max set value 8
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=9] run data modify entity @s data.agent.request.max set value 9
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=10] run data modify entity @s data.agent.request.max set value 10
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=11] run data modify entity @s data.agent.request.max set value 11
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=12] run data modify entity @s data.agent.request.max set value 12
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=13] run data modify entity @s data.agent.request.max set value 13
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=14] run data modify entity @s data.agent.request.max set value 14
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=15] run data modify entity @s data.agent.request.max set value 15
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=16] run data modify entity @s data.agent.request.max set value 16
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=17] run data modify entity @s data.agent.request.max set value 17
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=18] run data modify entity @s data.agent.request.max set value 18
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=19] run data modify entity @s data.agent.request.max set value 19
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=20] run data modify entity @s data.agent.request.max set value 20
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=21] run data modify entity @s data.agent.request.max set value 21
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=22] run data modify entity @s data.agent.request.max set value 22
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=23] run data modify entity @s data.agent.request.max set value 23
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=24] run data modify entity @s data.agent.request.max set value 24
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=25] run data modify entity @s data.agent.request.max set value 25
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=26] run data modify entity @s data.agent.request.max set value 26
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=27] run data modify entity @s data.agent.request.max set value 27
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=28] run data modify entity @s data.agent.request.max set value 28
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=29] run data modify entity @s data.agent.request.max set value 29
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=30] run data modify entity @s data.agent.request.max set value 30
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=31] run data modify entity @s data.agent.request.max set value 31
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=32] run data modify entity @s data.agent.request.max set value 32
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=33] run data modify entity @s data.agent.request.max set value 33
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=34] run data modify entity @s data.agent.request.max set value 34
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=35] run data modify entity @s data.agent.request.max set value 35
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=36] run data modify entity @s data.agent.request.max set value 36
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=37] run data modify entity @s data.agent.request.max set value 37
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=38] run data modify entity @s data.agent.request.max set value 38
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=39] run data modify entity @s data.agent.request.max set value 39
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=40] run data modify entity @s data.agent.request.max set value 40
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=41] run data modify entity @s data.agent.request.max set value 41
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=42] run data modify entity @s data.agent.request.max set value 42
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=43] run data modify entity @s data.agent.request.max set value 43
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=44] run data modify entity @s data.agent.request.max set value 44
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=45] run data modify entity @s data.agent.request.max set value 45
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=46] run data modify entity @s data.agent.request.max set value 46
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=47] run data modify entity @s data.agent.request.max set value 47
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=48] run data modify entity @s data.agent.request.max set value 48
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=49] run data modify entity @s data.agent.request.max set value 49
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=50] run data modify entity @s data.agent.request.max set value 50
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=51] run data modify entity @s data.agent.request.max set value 51
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=52] run data modify entity @s data.agent.request.max set value 52
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=53] run data modify entity @s data.agent.request.max set value 53
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=54] run data modify entity @s data.agent.request.max set value 54
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=55] run data modify entity @s data.agent.request.max set value 55
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=56] run data modify entity @s data.agent.request.max set value 56
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=57] run data modify entity @s data.agent.request.max set value 57
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=58] run data modify entity @s data.agent.request.max set value 58
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=59] run data modify entity @s data.agent.request.max set value 59
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=60] run data modify entity @s data.agent.request.max set value 60
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=61] run data modify entity @s data.agent.request.max set value 61
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=62] run data modify entity @s data.agent.request.max set value 62
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=63] run data modify entity @s data.agent.request.max set value 63
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=64] run data modify entity @s data.agent.request.max set value 64
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=65] run data modify entity @s data.agent.request.max set value 65
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=66] run data modify entity @s data.agent.request.max set value 66
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=67] run data modify entity @s data.agent.request.max set value 67
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=68] run data modify entity @s data.agent.request.max set value 68
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=69] run data modify entity @s data.agent.request.max set value 69
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=70] run data modify entity @s data.agent.request.max set value 70
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=71] run data modify entity @s data.agent.request.max set value 71
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=72] run data modify entity @s data.agent.request.max set value 72
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=73] run data modify entity @s data.agent.request.max set value 73
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=74] run data modify entity @s data.agent.request.max set value 74
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=75] run data modify entity @s data.agent.request.max set value 75
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=76] run data modify entity @s data.agent.request.max set value 76
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=77] run data modify entity @s data.agent.request.max set value 77
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=78] run data modify entity @s data.agent.request.max set value 78
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=79] run data modify entity @s data.agent.request.max set value 79
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=80] run data modify entity @s data.agent.request.max set value 80
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=81] run data modify entity @s data.agent.request.max set value 81
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=82] run data modify entity @s data.agent.request.max set value 82
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=83] run data modify entity @s data.agent.request.max set value 83
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=84] run data modify entity @s data.agent.request.max set value 84
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=85] run data modify entity @s data.agent.request.max set value 85
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=86] run data modify entity @s data.agent.request.max set value 86
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=87] run data modify entity @s data.agent.request.max set value 87
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=88] run data modify entity @s data.agent.request.max set value 88
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=89] run data modify entity @s data.agent.request.max set value 89
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=90] run data modify entity @s data.agent.request.max set value 90
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=91] run data modify entity @s data.agent.request.max set value 91
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=92] run data modify entity @s data.agent.request.max set value 92
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=93] run data modify entity @s data.agent.request.max set value 93
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=94] run data modify entity @s data.agent.request.max set value 94
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=95] run data modify entity @s data.agent.request.max set value 95
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=96] run data modify entity @s data.agent.request.max set value 96
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=97] run data modify entity @s data.agent.request.max set value 97
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=98] run data modify entity @s data.agent.request.max set value 98
execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size=99] run data modify entity @s data.agent.request.max set value 99
        function npcraft:inventory/add_staged with entity @s data.agent.request
        execute unless score #iv_ok np.tmp matches 1 run return run tellraw @a[tag=npcraft.actor] {"text":"Backpack full; held stack was not removed.","color":"yellow"}
        execute store success score #iv_removed np.tmp run item replace entity @a[tag=npcraft.actor,limit=1] weapon.mainhand with minecraft:air
        execute unless score #iv_removed np.tmp matches 1 run return 0
        function npcraft:inventory/commit
        tellraw @a[tag=npcraft.actor] {"text":"Held stack transferred to the 36-slot backpack.","color":"green"}
