# Generated by tools/generate_agent.py; edit the generator.
$execute if data entity @s data.agent.bag[$(i)].item.components."minecraft:unbreakable" run return 0
$execute if data entity @s data.agent.bag[$(i)].item.components."minecraft:enchantments" run return 0
$execute if data entity @s data.agent.bag[$(i)].item.components."minecraft:max_damage" run return 0
scoreboard players set #pick_damage np.tmp 0
$execute store result score #pick_damage np.tmp run data get entity @s data.agent.bag[$(i)].item.components."minecraft:damage"
$scoreboard players set #pick_limit np.tmp $(limit)
execute if score #pick_damage np.tmp >= #pick_limit np.tmp run return 0
execute if score #pick_damage np.tmp matches ..-1 run return 0
$scoreboard players set #tool_slot np.tmp $(i)
