# Generated by tools/generate_agent.py; edit the generator.
$data modify entity @s data.agent.hand set from entity @s data.agent.bag[$(i)].item
$data modify entity @s data.agent.equipped set value $(i)
