# Generated by tools/generate_agent.py; edit the generator.
$execute unless data storage npcraft:inventory bag[$(i)].item{id:"minecraft:$(kind)"} run return 0
# Crafting may consume ingredients with components, like vanilla recipes; full rollback on failure.
$execute store result score #iv_count np.tmp run data get storage npcraft:inventory bag[$(i)].item.count
scoreboard players operation #iv_take np.tmp = #iv_remaining np.tmp
scoreboard players operation #iv_take np.tmp < #iv_count np.tmp
scoreboard players operation #iv_remaining np.tmp -= #iv_take np.tmp
scoreboard players operation #iv_count np.tmp -= #iv_take np.tmp
$execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
$execute if score #iv_count np.tmp matches 0 run data modify storage npcraft:inventory bag[$(i)] set value {}
