# Generated by tools/generate_agent.py; edit the generator.
scoreboard players set #iv_ok np.tmp 0
execute unless score #iv_ready np.tmp matches 1 run return 0
$scoreboard players set #iv_remaining np.tmp $(count)
execute unless score #iv_remaining np.tmp matches 1..3564 run return 0
$data modify storage npcraft:inventory take set value {kind:"$(kind)"}
scoreboard players set #iv_i np.tmp 0
function npcraft:inventory/take_loop
execute if score #iv_remaining np.tmp matches 0 run scoreboard players set #iv_ok np.tmp 1
