# Generated by tools/generate_agent.py; edit the generator.
$execute unless data entity @s data.agent.bag[$(i)].item run return 0
scoreboard players set #wear np.tmp 0
$execute store result score #wear np.tmp run data get entity @s data.agent.bag[$(i)].item.components."minecraft:damage"
scoreboard players add #wear np.tmp 1
$execute store result entity @s data.agent.bag[$(i)].item.components."minecraft:damage" int 1 run scoreboard players get #wear np.tmp
$execute if data entity @s data.agent.bag[$(i)].item{id:"minecraft:wooden_pickaxe"} if score #wear np.tmp matches 59.. run data modify entity @s data.agent.bag[$(i)] set value {}
$execute if data entity @s data.agent.bag[$(i)].item{id:"minecraft:stone_pickaxe"} if score #wear np.tmp matches 131.. run data modify entity @s data.agent.bag[$(i)] set value {}
function npcraft:inventory/select_pick
