# Generated by tools/generate_agent.py; edit the generator.
data modify entity @s data.agent.blocked append from entity @s data.agent.target
execute if data entity @s data.agent.blocked[16] run data remove entity @s data.agent.blocked[0]
function npcraft:agent/invalidate
data modify entity @s data.agent.task set value "replanning_unreachable_target"
