# Generated by tools/generate_agent.py; edit the generator.
$execute unless loaded $(x) $(y) $(z) run return 0
$execute if data entity @s data.agent.blocked[{x:$(x),y:$(y),z:$(z)}] run return 0
$execute if data entity @s data.agent{resource:"oak_log"} if block $(x) $(y) $(z) minecraft:oak_log run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:oak_log"}
$execute if data entity @s data.agent{resource:"cobblestone"} if block $(x) $(y) $(z) minecraft:stone run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:stone"}
$execute if data entity @s data.agent{resource:"cobblestone"} if block $(x) $(y) $(z) minecraft:cobblestone run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:cobblestone"}
