# Generated by tools/generate_agent.py; edit the generator.
function npcraft:agent/init
execute if score #cmd np.tmp matches 20 run dialog show @a[tag=npcraft.actor] npcraft:agent
execute if score #cmd np.tmp matches 21 run function npcraft:agent/start
execute if score #cmd np.tmp matches 22 run function npcraft:inventory/give_held
execute if score #cmd np.tmp matches 23 run function npcraft:inventory/drop_all
execute if score #cmd np.tmp matches 24 run function npcraft:agent/status
execute if score #cmd np.tmp matches 25 run scoreboard players set @s np.mode 0
execute if score #cmd np.tmp matches 25 run function npcraft:agent/invalidate
