# Generated by tools/generate_agent.py; edit the generator.
execute store result score #failures np.tmp run data get entity @s data.agent.failures
scoreboard players add #failures np.tmp 1
execute store result entity @s data.agent.failures int 1 run scoreboard players get #failures np.tmp
execute if score #failures np.tmp matches 3.. run function npcraft:agent/blacklist
