# Generated by tools/generate_agent.py; edit the generator.
data modify entity @s data.agent.blocked set value []
scoreboard players operation #forget np.tmp = #now np.sys
scoreboard players add #forget np.tmp 400
execute store result entity @s data.agent.forget_at int 1 run scoreboard players get #forget np.tmp
