# Generated by tools/generate_agent.py; edit the generator.
data modify entity @s data.agent.task set value "backpack_full"
scoreboard players set @s np.status 20
scoreboard players operation @s np.next = #now np.sys
scoreboard players add @s np.next 100
