# Generated by tools/generate_agent.py; edit the generator.
execute unless data entity @s data.agent.target run function npcraft:agent/scan
execute unless data entity @s data.agent.target run return run function npcraft:agent/no_resource
function npcraft:agent/move_target with entity @s data.agent.target
