# Generated by tools/generate_agent.py; edit the generator.
data remove entity @s data.agent.target
data remove entity @s data.target
data modify entity @s data.agent.failures set value 0
scoreboard players set @s np.dig 0
