# Generated by tools/generate_agent.py; edit the generator.
$execute unless block $(x) $(y) $(z) $(kind) run return run function npcraft:agent/invalidate
# Try an adjacent standing cell at the plot level, preserving line-of-sight/reach at commit.
data modify entity @s data.dest set from entity @s data.agent.target
data modify entity @s data.dest.y set from entity @s data.plot.y
data modify entity @s data.dest.range set value 1
function npcraft:nav/plan
execute if score @s np.status matches 1 run data modify entity @s data.agent.failures set value 0
execute if score @s np.status matches 4 run return run function npcraft:agent/failed
execute if score #arrived np.tmp matches 1 run function npcraft:action/mine
