# Generated by tools/generate_agent.py; edit the generator.
data modify entity @s data.agent.task set value "searching_permitted_plot"
execute unless data entity @s data.agent{scanned:196} run return 0
data modify entity @s data.agent.task set value "resource_unavailable_waiting"
scoreboard players operation @s np.next = #now np.sys
scoreboard players add @s np.next 100
