# Generated by tools/generate_agent.py; edit the generator.
$data modify entity @s data.agent.target set value {x:$(x),y:$(y),z:$(z),kind:"$(kind)"}
data modify entity @s data.agent.scanned set value 0
data modify entity @s data.agent.failures set value 0
scoreboard players set @s np.dig 0
