# Generated by tools/generate_agent.py; edit the generator.
execute unless data entity @s data.plot run return run tellraw @a[tag=npcraft.actor] {"text":"Assign a plot first. Autonomous work may mine oak, stone and cobblestone inside it and place one workbench at its center.","color":"yellow"}
function npcraft:agent/init
function npcraft:agent/invalidate
data modify entity @s data.agent.task set value "planning_stone_kit"
scoreboard players set @s np.mode 4
scoreboard players set @s np.next 0
