# Generated by tools/generate_agent.py; edit the generator.
tellraw @a[tag=npcraft.actor] [{"text":"Agent task: ","color":"aqua"},{"nbt":"data.agent.task","entity":"@s"}]
tellraw @a[tag=npcraft.actor] [{"text":"Backpack (36 slots): ","color":"gray"},{"nbt":"data.agent.bag","entity":"@s"}]
