# Generated by tools/generate_agent.py; edit the generator.
function npcraft:agent/init
execute unless data entity @s data.agent{schema:1} run return 0
execute unless data entity @s data.plot run return run scoreboard players set @s np.status 7
execute unless function npcraft:nav/cell_safe run return run scoreboard players set @s np.status 4
execute store result score #forget np.tmp run data get entity @s data.agent.forget_at
execute if score #now np.sys >= #forget np.tmp run function npcraft:agent/forget
function npcraft:planner/choose
