# Generated by tools/generate_agent.py; edit the generator.
execute unless function npcraft:craft/station_valid run return 0
return run function npcraft:craft/station_reach with entity @s data.agent.station
