# Generated by tools/generate_agent.py; edit the generator.
# Choose the center only; blocked sites report a reason rather than overwrite buildings.
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless function npcraft:nav/cell_safe run return run function npcraft:craft/site_blocked
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @a[distance=..0.9] run return run function npcraft:craft/site_blocked
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return run function npcraft:craft/site_blocked
data modify entity @s data.dest set from entity @s data.plot
data modify entity @s data.dest.range set value 1
function npcraft:nav/plan
execute unless score #arrived np.tmp matches 1 run return 0
function npcraft:inventory/begin
function npcraft:inventory/take_staged {kind:"crafting_table",count:1}
execute unless score #iv_ok np.tmp matches 1 run return 0
function npcraft:action/place_table with entity @s data.agent.target
