# Generated by tools/generate_agent.py; edit the generator.
data modify entity @s data.agent.task set value "clear_plot_center_for_workbench"
scoreboard players operation @s np.next = #now np.sys
scoreboard players add @s np.next 40
