# Generated by tools/generate_agent.py; edit the generator.
$execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless entity @s[distance=..3] run return 0
data modify entity @s data.target set from entity @s data.agent.station
function npcraft:work/sight with entity @s data.target
execute unless score #visible np.tmp matches 1 run return 0
return 1
