# Generated by tools/generate_agent.py; edit the generator.
execute unless data entity @s data.agent.station run return 0
return run function npcraft:craft/station_check with entity @s data.agent.station
