#!/usr/bin/env python3
"""Generate the bounded vanilla agent runtime. No Python runs inside Minecraft.

Canonical definitions live here; generated mcfunctions are committed and audited.
Transactions stage one 36-slot backpack before publishing any inventory change.
Planning is a finite dependency graph, not an LLM or an unrestricted GOAP solver.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
SLOTS = 36  # Nine of these are hotbar-equivalent, not 36 + 9.
RECIPES = {
    'oak_planks': (4, 64, False, [('oak_log', 1)]),
    'stick': (4, 64, False, [('oak_planks', 2)]),
    'crafting_table': (1, 64, False, [('oak_planks', 4)]),
    'wooden_pickaxe': (1, 1, True, [('oak_planks', 3), ('stick', 2)]),
    'stone_pickaxe': (1, 1, True, [('cobblestone', 3), ('stick', 2)]),
    'stone_sword': (1, 1, True, [('cobblestone', 2), ('stick', 1)]),
    'stone_axe': (1, 1, True, [('cobblestone', 3), ('stick', 2)]),
    'furnace': (1, 64, True, [('cobblestone', 8)]),
}

def resources() -> dict[str, str]:
    out: dict[str, str] = {}
    def fn(name: str, body: str):
        out[f'datapack/data/npcraft/function/{name}.mcfunction'] = (
            '# Generated by tools/generate_agent.py; edit the generator.\n' + dedent(body).strip() + '\n')
    def js(name: str, value):
        out[f'datapack/data/npcraft/{name}.json'] = json.dumps(value, indent=2) + '\n'

    fn('agent/init', '''
        execute if data entity @s data.agent run return 0
        data modify entity @s data.agent set value {schema:1,bag:[],scan:0,scanned:0,blocked:[],forget_at:0,failures:0,goal:"stone_kit",task:"idle",crafted:0,mined:0}
    ''' + '\n'.join('data modify entity @s data.agent.bag append value {}' for _ in range(SLOTS)))
    fn('inventory/begin', '''
        function npcraft:agent/init
        data modify storage npcraft:inventory bag set from entity @s data.agent.bag
        scoreboard players set #iv_ok np.tmp 0
    ''')
    fn('inventory/commit', '''
        execute unless score #iv_ok np.tmp matches 1 run return 0
        data modify entity @s data.agent.bag set from storage npcraft:inventory bag
        return 1
    ''')
    fn('inventory/add', '''
        function npcraft:inventory/begin
        function npcraft:inventory/add_staged with entity @s data.agent.request
        execute if score #iv_ok np.tmp matches 1 run function npcraft:inventory/commit
    ''')
    fn('inventory/add_staged', '''
        scoreboard players set #iv_ok np.tmp 0
        $data modify storage npcraft:inventory incoming set value $(stack)
        $scoreboard players set #iv_max np.tmp $(max)
        execute unless score #iv_max np.tmp matches 1..99 run return 0
        execute unless data storage npcraft:inventory incoming.id run return 0
        scoreboard players set #iv_remaining np.tmp 0
        execute store result score #iv_remaining np.tmp run data get storage npcraft:inventory incoming.count
        execute unless score #iv_remaining np.tmp matches 1..3564 run return 0
        data modify storage npcraft:inventory key set from storage npcraft:inventory incoming
        data remove storage npcraft:inventory key.count
        scoreboard players set #iv_i np.tmp 0
        function npcraft:inventory/add_loop
        scoreboard players set #iv_i np.tmp 0
        function npcraft:inventory/empty_loop
        execute if score #iv_remaining np.tmp matches 0 run scoreboard players set #iv_ok np.tmp 1
    ''')
    for mode in ('add', 'empty'):
        fn(f'inventory/{mode}_loop', f'''
            execute if score #iv_remaining np.tmp matches 0 run return 0
            execute if score #iv_i np.tmp matches {SLOTS}.. run return 0
            execute store result storage npcraft:inventory cursor.i int 1 run scoreboard players get #iv_i np.tmp
            function npcraft:inventory/{mode}_slot with storage npcraft:inventory cursor
            scoreboard players add #iv_i np.tmp 1
            function npcraft:inventory/{mode}_loop
        ''')
    fn('inventory/add_slot', '''
        $execute unless data storage npcraft:inventory bag[$(i)].item run return 0
        $execute store result score #iv_limit np.tmp run data get storage npcraft:inventory bag[$(i)].max
        execute unless score #iv_limit np.tmp = #iv_max np.tmp run return 0
        $data modify storage npcraft:inventory probe set from storage npcraft:inventory bag[$(i)].item
        data remove storage npcraft:inventory probe.count
        execute store success score #iv_different np.tmp run data modify storage npcraft:inventory probe set from storage npcraft:inventory key
        execute if score #iv_different np.tmp matches 1 run return 0
        $execute store result score #iv_count np.tmp run data get storage npcraft:inventory bag[$(i)].item.count
        scoreboard players operation #iv_room np.tmp = #iv_max np.tmp
        scoreboard players operation #iv_room np.tmp -= #iv_count np.tmp
        execute unless score #iv_room np.tmp matches 1.. run return 0
        scoreboard players operation #iv_room np.tmp < #iv_remaining np.tmp
        scoreboard players operation #iv_count np.tmp += #iv_room np.tmp
        scoreboard players operation #iv_remaining np.tmp -= #iv_room np.tmp
        $execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
    ''')
    fn('inventory/empty_slot', '''
        $execute if data storage npcraft:inventory bag[$(i)].item run return 0
        scoreboard players operation #iv_count np.tmp = #iv_remaining np.tmp
        scoreboard players operation #iv_count np.tmp < #iv_max np.tmp
        $data modify storage npcraft:inventory bag[$(i)] set value {}
        $data modify storage npcraft:inventory bag[$(i)].item set from storage npcraft:inventory incoming
        $execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
        $execute store result storage npcraft:inventory bag[$(i)].max int 1 run scoreboard players get #iv_max np.tmp
        scoreboard players operation #iv_remaining np.tmp -= #iv_count np.tmp
    ''')
    fn('inventory/count', '''
        scoreboard players set #iv_have np.tmp 0
        $execute as @s run function npcraft:inventory/count_all {kind:"$(kind)"}
    ''')
    # A fixed unrolled read avoids shared cursor corruption in recursive planner dependencies.
    fn('inventory/count_all', '\n'.join(
        f'$execute if data entity @s data.agent.bag[{i}].item{{id:"minecraft:$(kind)"}} store result score #iv_one np.tmp run data get entity @s data.agent.bag[{i}].item.count\n'
        f'$execute if data entity @s data.agent.bag[{i}].item{{id:"minecraft:$(kind)"}} run scoreboard players operation #iv_have np.tmp += #iv_one np.tmp'
        for i in range(SLOTS)))
    fn('inventory/take_staged', '''
        scoreboard players set #iv_ok np.tmp 0
        $scoreboard players set #iv_remaining np.tmp $(count)
        execute unless score #iv_remaining np.tmp matches 1..3564 run return 0
        $data modify storage npcraft:inventory take set value {kind:"$(kind)"}
        scoreboard players set #iv_i np.tmp 0
        function npcraft:inventory/take_loop
        execute if score #iv_remaining np.tmp matches 0 run scoreboard players set #iv_ok np.tmp 1
    ''')
    fn('inventory/take_loop', f'''
        execute if score #iv_remaining np.tmp matches 0 run return 0
        execute if score #iv_i np.tmp matches {SLOTS}.. run return 0
        execute store result storage npcraft:inventory take.i int 1 run scoreboard players get #iv_i np.tmp
        function npcraft:inventory/take_slot with storage npcraft:inventory take
        scoreboard players add #iv_i np.tmp 1
        function npcraft:inventory/take_loop
    ''')
    fn('inventory/take_slot', '''
        $execute unless data storage npcraft:inventory bag[$(i)].item{id:"minecraft:$(kind)"} run return 0
        # Crafting may consume ingredients with components, like vanilla recipes; full rollback on failure.
        $execute store result score #iv_count np.tmp run data get storage npcraft:inventory bag[$(i)].item.count
        scoreboard players operation #iv_take np.tmp = #iv_remaining np.tmp
        scoreboard players operation #iv_take np.tmp < #iv_count np.tmp
        scoreboard players operation #iv_remaining np.tmp -= #iv_take np.tmp
        scoreboard players operation #iv_count np.tmp -= #iv_take np.tmp
        $execute store result storage npcraft:inventory bag[$(i)].item.count int 1 run scoreboard players get #iv_count np.tmp
        $execute if score #iv_count np.tmp matches 0 run data modify storage npcraft:inventory bag[$(i)] set value {}
    ''')
    fn('inventory/give_held', '''
        execute unless items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand * run return 0
        function npcraft:inventory/begin
        data modify entity @s data.agent.request set value {max:0}
        data modify entity @s data.agent.request.stack set from entity @a[tag=npcraft.actor,limit=1] SelectedItem
    ''' + '\n'.join(f'execute if items entity @a[tag=npcraft.actor,limit=1] weapon.mainhand *[minecraft:max_stack_size={size}] run data modify entity @s data.agent.request.max set value {size}' for size in range(1, 100)) + '''
        function npcraft:inventory/add_staged with entity @s data.agent.request
        execute unless score #iv_ok np.tmp matches 1 run return run tellraw @a[tag=npcraft.actor] {"text":"Backpack full; held stack was not removed.","color":"yellow"}
        execute store success score #iv_removed np.tmp run item replace entity @a[tag=npcraft.actor,limit=1] weapon.mainhand with minecraft:air
        execute unless score #iv_removed np.tmp matches 1 run return 0
        function npcraft:inventory/commit
        tellraw @a[tag=npcraft.actor] {"text":"Held stack transferred to the 36-slot backpack.","color":"green"}
    ''')
    fn('inventory/drop_all', '''
        execute unless data entity @s data.agent run return 0
        scoreboard players set #iv_i np.tmp 0
        function npcraft:inventory/drop_loop
        data remove entity @s data.agent.hand
    ''')
    fn('inventory/drop_loop', f'''
        execute if score #iv_i np.tmp matches {SLOTS}.. run return 0
        execute store result storage npcraft:inventory drop.i int 1 run scoreboard players get #iv_i np.tmp
        function npcraft:inventory/drop_slot with storage npcraft:inventory drop
        scoreboard players add #iv_i np.tmp 1
        function npcraft:inventory/drop_loop
    ''')
    fn('inventory/drop_slot', '''
        $execute unless data entity @s data.agent.bag[$(i)].item run return 0
        $data modify storage npcraft:inventory drop.item set from entity @s data.agent.bag[$(i)].item
        function npcraft:inventory/drop_item with storage npcraft:inventory drop
    ''')
    fn('inventory/drop_item', '''
        $execute store success score #iv_dropped np.tmp run summon minecraft:item ~ ~0.5 ~ {Item:$(item),PickupDelay:0s}
        $execute if score #iv_dropped np.tmp matches 1 run data modify entity @s data.agent.bag[$(i)] set value {}
    ''')
    fn('inventory/select_pick', '''
        data remove entity @s data.agent.hand
        scoreboard players set #tool_slot np.tmp -1
    ''' + '\n'.join(
        f'execute if data entity @s data.agent.bag[{i}].item{{id:"minecraft:{tool}"}} run scoreboard players set #tool_slot np.tmp {i}'
        for tool in ('wooden_pickaxe', 'stone_pickaxe') for i in range(SLOTS)) + '''
        execute unless score #tool_slot np.tmp matches 0..35 run return 0
        execute store result storage npcraft:inventory tool.i int 1 run scoreboard players get #tool_slot np.tmp
        function npcraft:inventory/select_slot with storage npcraft:inventory tool
    ''')
    fn('inventory/select_slot', '''
        $data modify entity @s data.agent.hand set from entity @s data.agent.bag[$(i)].item
        $data modify entity @s data.agent.equipped set value $(i)
    ''')
    fn('inventory/wear', '''
        $execute unless data entity @s data.agent.bag[$(i)].item run return 0
        scoreboard players set #wear np.tmp 0
        $execute store result score #wear np.tmp run data get entity @s data.agent.bag[$(i)].item.components."minecraft:damage"
        scoreboard players add #wear np.tmp 1
        $execute store result entity @s data.agent.bag[$(i)].item.components."minecraft:damage" int 1 run scoreboard players get #wear np.tmp
        $execute if data entity @s data.agent.bag[$(i)].item{id:"minecraft:wooden_pickaxe"} if score #wear np.tmp matches 59.. run data modify entity @s data.agent.bag[$(i)] set value {}
        $execute if data entity @s data.agent.bag[$(i)].item{id:"minecraft:stone_pickaxe"} if score #wear np.tmp matches 131.. run data modify entity @s data.agent.bag[$(i)] set value {}
        function npcraft:inventory/select_pick
    ''')

    # Only these finite materials may be mined. No global dig/loot commands.
    fn('action/bounds', '''
        data modify entity @s data.target set from entity @s data.agent.target
        return run function npcraft:work/in_bounds
    ''')
    fn('action/check', '''
        execute unless dimension minecraft:overworld run return 0
        execute unless function npcraft:action/bounds run return 0
        $execute unless loaded $(x) $(y) $(z) run return 0
        $execute unless block $(x) $(y) $(z) $(kind) run return 0
        # Never harvest the support underneath any NPC body or player.
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~1 ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return 0
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~1 ~0.5 if entity @a[distance=..0.9] run return 0
        function npcraft:work/sight with entity @s data.agent.target
        execute unless score #visible np.tmp matches 1 run return 0
        return 1
    ''')
    fn('action/valid', 'return run function npcraft:action/check with entity @s data.agent.target')
    fn('action/mine', '''
        execute unless function npcraft:action/valid run return run function npcraft:agent/failed
        # Whitelist dispatch validates drop/tool rules instead of trusting a supplied drop ID.
        execute if data entity @s data.agent.target{kind:"minecraft:oak_log"} run return run function npcraft:action/log
        execute if data entity @s data.agent.target{kind:"minecraft:stone"} run return run function npcraft:action/stone
        execute if data entity @s data.agent.target{kind:"minecraft:cobblestone"} run return run function npcraft:action/stone
        return 0
    ''')
    fn('action/log', '''
        data remove entity @s data.agent.hand
        scoreboard players set #tool_slot np.tmp -1
        data modify entity @s data.agent.request set value {stack:{id:"minecraft:oak_log",count:1},max:64}
        data modify entity @s data.agent.duration set value 60
        function npcraft:action/cut
    ''')
    fn('action/stone', '''
        function npcraft:inventory/select_pick
        execute unless score #tool_slot np.tmp matches 0..35 run return run function npcraft:agent/invalidate
        data modify entity @s data.agent.request set value {stack:{id:"minecraft:cobblestone",count:1},max:64}
        data modify entity @s data.agent.duration set value 30
        function npcraft:action/cut
    ''')
    fn('action/cut', '''
        scoreboard players set @s np.status 3
        function npcraft:work/swing with entity @s data
        execute unless score @s np.dig matches 1.. run function npcraft:action/start
        execute if score #now np.sys < @s np.dig run return 0
        function npcraft:inventory/begin
        function npcraft:inventory/add_staged with entity @s data.agent.request
        execute unless score #iv_ok np.tmp matches 1 run return run function npcraft:agent/full
        function npcraft:action/commit with entity @s data.agent.target
    ''')
    fn('action/start', '''
        scoreboard players operation @s np.dig = #now np.sys
        execute store result score #duration np.tmp run data get entity @s data.agent.duration
        scoreboard players operation @s np.dig += #duration np.tmp
    ''')
    fn('action/commit', '''
        # Staged inventory is unpublished until removal succeeds; repeat all geometric checks.
        execute unless score #iv_ok np.tmp matches 1 run return 0
        execute unless function npcraft:action/valid run return run function npcraft:agent/failed
        $execute store success score #removed np.tmp run setblock $(x) $(y) $(z) minecraft:air
        execute unless score #removed np.tmp matches 1 run return 0
        function npcraft:inventory/commit
        execute if score #tool_slot np.tmp matches 0..35 store result storage npcraft:inventory tool.i int 1 run scoreboard players get #tool_slot np.tmp
        execute if score #tool_slot np.tmp matches 0..35 run function npcraft:inventory/wear with storage npcraft:inventory tool
        execute store result score #mined np.tmp run data get entity @s data.agent.mined
        scoreboard players add #mined np.tmp 1
        execute store result entity @s data.agent.mined int 1 run scoreboard players get #mined np.tmp
        function npcraft:agent/invalidate
    ''')
    fn('agent/invalidate', '''
        data remove entity @s data.agent.target
        data remove entity @s data.target
        data modify entity @s data.agent.failures set value 0
        scoreboard players set @s np.dig 0
    ''')
    fn('agent/full', '''
        data modify entity @s data.agent.task set value "backpack_full"
        scoreboard players set @s np.status 20
        scoreboard players operation @s np.next = #now np.sys
        scoreboard players add @s np.next 100
    ''')
    fn('agent/failed', '''
        execute store result score #failures np.tmp run data get entity @s data.agent.failures
        scoreboard players add #failures np.tmp 1
        execute store result entity @s data.agent.failures int 1 run scoreboard players get #failures np.tmp
        execute if score #failures np.tmp matches 3.. run function npcraft:agent/blacklist
    ''')
    fn('agent/blacklist', '''
        data modify entity @s data.agent.blocked append from entity @s data.agent.target
        execute if data entity @s data.agent.blocked[16] run data remove entity @s data.agent.blocked[0]
        function npcraft:agent/invalidate
        data modify entity @s data.agent.task set value "replanning_unreachable_target"
    ''')
    fn('agent/scan', '''
        scoreboard players set #scan_budget np.tmp 8
        function npcraft:agent/scan_loop
    ''')
    # Reuse the tested finite cube index math, but keep the scan progress distinct.
    old_scan = (ROOT / 'datapack/data/npcraft/function/work/scan_loop.mcfunction').read_text()
    scan = old_scan.replace('data.target', 'data.agent.target').replace('data.scanned', 'data.agent.scanned').replace('data.scan', 'data.agent.scan')
    scan = scan.replace('data{scanned', 'data.agent{scanned').replace('npcraft:work/candidate', 'npcraft:agent/candidate').replace('npcraft:work/scan_loop', 'npcraft:agent/scan_loop')
    fn('agent/scan_loop', scan)
    fn('agent/candidate', '''
        $execute unless loaded $(x) $(y) $(z) run return 0
        $execute if data entity @s data.agent.blocked[{x:$(x),y:$(y),z:$(z)}] run return 0
        $execute if data entity @s data.agent{resource:"oak_log"} if block $(x) $(y) $(z) minecraft:oak_log run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:oak_log"}
        $execute if data entity @s data.agent{resource:"cobblestone"} if block $(x) $(y) $(z) minecraft:stone run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:stone"}
        $execute if data entity @s data.agent{resource:"cobblestone"} if block $(x) $(y) $(z) minecraft:cobblestone run function npcraft:agent/select {x:$(x),y:$(y),z:$(z),kind:"minecraft:cobblestone"}
    ''')
    fn('agent/select', '''
        $data modify entity @s data.agent.target set value {x:$(x),y:$(y),z:$(z),kind:"$(kind)"}
        data modify entity @s data.agent.scanned set value 0
        data modify entity @s data.agent.failures set value 0
        scoreboard players set @s np.dig 0
    ''')
    fn('agent/gather', '''
        execute unless data entity @s data.agent.target run function npcraft:agent/scan
        execute unless data entity @s data.agent.target run return run function npcraft:agent/no_resource
        function npcraft:agent/move_target with entity @s data.agent.target
    ''')
    fn('agent/no_resource', '''
        data modify entity @s data.agent.task set value "searching_permitted_plot"
        execute unless data entity @s data.agent{scanned:196} run return 0
        data modify entity @s data.agent.task set value "resource_unavailable_waiting"
        scoreboard players operation @s np.next = #now np.sys
        scoreboard players add @s np.next 100
    ''')
    fn('agent/move_target', '''
        $execute unless block $(x) $(y) $(z) $(kind) run return run function npcraft:agent/invalidate
        # Try an adjacent standing cell at the plot level, preserving line-of-sight/reach at commit.
        data modify entity @s data.dest set from entity @s data.agent.target
        data modify entity @s data.dest.y set from entity @s data.plot.y
        data modify entity @s data.dest.range set value 1
        function npcraft:nav/plan
        execute if score @s np.status matches 1 run data modify entity @s data.agent.failures set value 0
        execute if score @s np.status matches 4 run return run function npcraft:agent/failed
        execute if score #arrived np.tmp matches 1 run function npcraft:action/mine
    ''')

    # Workbench is an actual block. Place only inside the plot on approved ground.
    fn('craft/station_valid', '''
        execute unless data entity @s data.agent.station run return 0
        return run function npcraft:craft/station_check with entity @s data.agent.station
    ''')
    fn('craft/station_check', '''
        $execute unless loaded $(x) $(y) $(z) run return 0
        $execute unless block $(x) $(y) $(z) minecraft:crafting_table run return 0
        return 1
    ''')
    fn('craft/near_station', '''
        execute unless function npcraft:craft/station_valid run return 0
        return run function npcraft:craft/station_reach with entity @s data.agent.station
    ''')
    fn('craft/station_reach', '''
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless entity @s[distance=..3] run return 0
        data modify entity @s data.target set from entity @s data.agent.station
        function npcraft:work/sight with entity @s data.target
        execute unless score #visible np.tmp matches 1 run return 0
        return 1
    ''')
    fn('craft/place_station', '''
        data modify entity @s data.agent.target set from entity @s data.plot
        function npcraft:craft/place_try with entity @s data.agent.target
    ''')
    fn('craft/place_try', '''
        # Choose the center only; blocked sites report a reason rather than overwrite buildings.
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless function npcraft:nav/cell_safe run return run function npcraft:craft/site_blocked
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @a[distance=..0.9] run return run function npcraft:craft/site_blocked
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return run function npcraft:craft/site_blocked
        data modify entity @s data.dest set from entity @s data.plot
        data modify entity @s data.dest.range set value 1
        function npcraft:nav/plan
        execute unless score #arrived np.tmp matches 1 run return 0
        function npcraft:inventory/begin
        function npcraft:inventory/take_staged {kind:"crafting_table",count:1}
        execute unless score #iv_ok np.tmp matches 1 run return 0
        function npcraft:action/place_table with entity @s data.agent.target
    ''')
    fn('craft/site_blocked', '''
        data modify entity @s data.agent.task set value "clear_plot_center_for_workbench"
        scoreboard players operation @s np.next = #now np.sys
        scoreboard players add @s np.next 40
    ''')
    fn('action/place_table', '''
        execute unless score #iv_ok np.tmp matches 1 run return 0
        execute unless function npcraft:action/bounds run return 0
        $execute unless block $(x) $(y) $(z) minecraft:air run return 0
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 unless entity @s[distance=0.9..2] run return 0
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @a[distance=..0.9] run return 0
        $execute positioned $(x) $(y) $(z) align xyz positioned ~0.5 ~ ~0.5 if entity @e[tag=npcraft.body,distance=..0.9] run return 0
        $execute store success score #placed np.tmp run setblock $(x) $(y) $(z) minecraft:crafting_table keep
        execute unless score #placed np.tmp matches 1 run return 0
        function npcraft:inventory/commit
        data modify entity @s data.agent.station set from entity @s data.agent.target
        function npcraft:agent/invalidate
    ''')
    for kind, (amount, maximum, station, ingredients) in RECIPES.items():
        lines = []
        if station:
            lines.append('execute unless function npcraft:craft/near_station run return 0')
        lines.append('function npcraft:inventory/begin')
        for ingredient, quantity in ingredients:
            lines += [f'function npcraft:inventory/take_staged {{kind:"{ingredient}",count:{quantity}}}',
                      'execute unless score #iv_ok np.tmp matches 1 run return 0']
        lines += [f'function npcraft:inventory/add_staged {{stack:{{id:"minecraft:{kind}",count:{amount}}},max:{maximum}}}',
                  'execute unless score #iv_ok np.tmp matches 1 run return 0',
                  'function npcraft:inventory/commit',
                  'execute store result score #crafted np.tmp run data get entity @s data.agent.crafted',
                  'scoreboard players add #crafted np.tmp 1',
                  'execute store result entity @s data.agent.crafted int 1 run scoreboard players get #crafted np.tmp',
                  f'data modify entity @s data.agent.task set value "crafted_{kind}"',
                  'return 1']
        fn(f'craft/recipes/{kind}', '\n'.join(lines))

    # Compile finite ingredient dependencies. Exactly one leaf action per brain visit.
    built: set[tuple[str, int]] = set()
    def need(kind: str, count: int):
        key = (kind, count)
        if key in built:
            return
        built.add(key)
        lines = [f'function npcraft:inventory/count {{kind:"{kind}"}}',
                 f'execute if score #iv_have np.tmp matches {count}.. run return 1']
        if kind in ('oak_log', 'cobblestone'):
            if kind == 'cobblestone':
                lines += ['function npcraft:inventory/select_pick',
                          'execute unless score #tool_slot np.tmp matches 0..35 run return run function npcraft:planner/need/wooden_pickaxe_1']
                need('wooden_pickaxe', 1)
            lines += [f'execute unless data entity @s data.agent{{resource:"{kind}"}} run function npcraft:agent/invalidate',
                      f'data modify entity @s data.agent.resource set value "{kind}"',
                      f'data modify entity @s data.agent.task set value "gather_{kind}"',
                      'function npcraft:agent/gather', 'return 0']
        else:
            amount, maximum, station, ingredients = RECIPES[kind]
            if station:
                lines.append('execute unless function npcraft:craft/station_valid run return run function npcraft:planner/station')
            for ingredient, quantity in ingredients:
                need(ingredient, quantity)
                lines += [f'function npcraft:inventory/count {{kind:"{ingredient}"}}',
                          f'execute unless score #iv_have np.tmp matches {quantity}.. run return run function npcraft:planner/need/{ingredient}_{quantity}']
            if station:
                lines += ['data modify entity @s data.dest set from entity @s data.agent.station',
                          'data modify entity @s data.dest.range set value 1',
                          'function npcraft:nav/plan',
                          'execute unless score #arrived np.tmp matches 1 run return 0']
            lines += [f'function npcraft:craft/recipes/{kind}', 'return 0']
        fn(f'planner/need/{kind}_{count}', '\n'.join(lines))
    for goal in ('stone_pickaxe', 'stone_sword', 'stone_axe', 'furnace', 'crafting_table'):
        need(goal, 1)
    fn('planner/station', '''
        function npcraft:inventory/count {kind:"crafting_table"}
        execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/crafting_table_1
        data modify entity @s data.agent.task set value "place_workbench_at_plot_center"
        function npcraft:craft/place_station
    ''')
    fn('agent/tick', '''
        function npcraft:agent/init
        execute unless data entity @s data.agent{schema:1} run return 0
        execute unless data entity @s data.plot run return run scoreboard players set @s np.status 7
        execute unless function npcraft:nav/cell_safe run return run scoreboard players set @s np.status 4
        execute store result score #forget np.tmp run data get entity @s data.agent.forget_at
        execute if score #now np.sys >= #forget np.tmp run function npcraft:agent/forget
        function npcraft:planner/choose
    ''')
    fn('agent/forget', '''
        data modify entity @s data.agent.blocked set value []
        scoreboard players operation #forget np.tmp = #now np.sys
        scoreboard players add #forget np.tmp 400
        execute store result entity @s data.agent.forget_at int 1 run scoreboard players get #forget np.tmp
    ''')
    fn('planner/choose', '''
        # Utility order: essential mining capability, weapon, efficient timber tool, furnace.
        # Re-evaluate actual inventory every visit; no persistent fake technology stage.
        function npcraft:inventory/count {kind:"stone_pickaxe"}
        execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stone_pickaxe_1
        function npcraft:inventory/count {kind:"stone_sword"}
        execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stone_sword_1
        function npcraft:inventory/count {kind:"stone_axe"}
        execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stone_axe_1
        function npcraft:inventory/count {kind:"furnace"}
        execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/furnace_1
        data modify entity @s data.agent.task set value "stone_kit_ready"
        function npcraft:inventory/select_pick
        scoreboard players operation @s np.next = #now np.sys
        scoreboard players add @s np.next 40
    ''')
    fn('agent/start', '''
        execute unless data entity @s data.plot run return run tellraw @a[tag=npcraft.actor] {"text":"Assign a plot first. Autonomous work may mine oak, stone and cobblestone inside it and place one workbench at its center.","color":"yellow"}
        function npcraft:agent/init
        function npcraft:agent/invalidate
        data modify entity @s data.agent.task set value "planning_stone_kit"
        scoreboard players set @s np.mode 4
        scoreboard players set @s np.next 0
    ''')
    fn('agent/status', '''
        tellraw @a[tag=npcraft.actor] [{"text":"Agent task: ","color":"aqua"},{"nbt":"data.agent.task","entity":"@s"}]
        tellraw @a[tag=npcraft.actor] [{"text":"Backpack (36 slots): ","color":"gray"},{"nbt":"data.agent.bag","entity":"@s"}]
    ''')
    fn('agent/commands', '''
        function npcraft:agent/init
        execute if score #cmd np.tmp matches 20 run dialog show @a[tag=npcraft.actor] npcraft:agent
        execute if score #cmd np.tmp matches 21 run function npcraft:agent/start
        execute if score #cmd np.tmp matches 22 run function npcraft:inventory/give_held
        execute if score #cmd np.tmp matches 23 run function npcraft:inventory/drop_all
        execute if score #cmd np.tmp matches 24 run function npcraft:agent/status
        execute if score #cmd np.tmp matches 25 run scoreboard players set @s np.mode 0
        execute if score #cmd np.tmp matches 25 run function npcraft:agent/invalidate
    ''')
    labels = [('Build stone kit', 21), ('Stop autonomous work',25), ('Store held stack',22), ('Return backpack (drops)',23), ('Task / inventory status',24), ('Legacy companion panel',1)]
    js('dialog/agent', {
        'type':'minecraft:multi_action', 'title':'NPCraft | Autonomous agent', 'pause':False, 'columns':2,
        'body':[{'type':'minecraft:plain_message','width':360,'contents':'Experimental: gather oak and stone, craft a workbench and stone kit. Uses your assigned 7 x 7 x 4 plot; ALL eligible blocks inside are permitted. Keep its center empty for a workbench. No food, combat or free-world exploration yet.'}],
        'actions':[{'label':label,'action':{'type':'run_command','command':f'trigger npcraft set {cmd}'}} for label,cmd in labels],
        'exit_action':{'label':'Close'}})
    return out


def generate(root: Path = ROOT, check: bool = False) -> list[str]:
    changed = []
    for relative, content in resources().items():
        target = root / relative
        if not target.is_file() or target.read_text(encoding='utf-8') != content:
            changed.append(relative)
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding='utf-8', newline='\n')
    return changed

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = generate(check=args.check)
    if args.check and changed:
        print('\n'.join(changed))
        raise SystemExit('Generated resources differ. Run python tools/generate_agent.py.')
    print(f'Agent runtime: {len(resources())} generated resources; {len(changed)} changed.')
