# Generated by tools/generate_agent.py; edit the generator.
# Utility order: essential mining capability, weapon, efficient timber tool, furnace.
# Re-evaluate actual inventory every visit; no persistent fake technology stage.
function npcraft:inventory/select_pick
execute unless data entity @s data.agent.hand{id:"minecraft:stone_pickaxe"} run return run function npcraft:planner/need/stone_pickaxe_1
function npcraft:inventory/count {kind:"stone_sword"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stone_sword_1
function npcraft:inventory/count {kind:"stone_axe"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/stone_axe_1
function npcraft:inventory/count {kind:"furnace"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/furnace_1
data modify entity @s data.agent.task set value "stone_kit_ready"
function npcraft:inventory/select_pick
scoreboard players operation @s np.next = #now np.sys
scoreboard players add @s np.next 40
