# Generated by tools/generate_agent.py; edit the generator.
function npcraft:inventory/count {kind:"crafting_table"}
execute unless score #iv_have np.tmp matches 1.. run return run function npcraft:planner/need/crafting_table_1
data modify entity @s data.agent.task set value "place_workbench_at_plot_center"
function npcraft:craft/place_station
